# Generated by Django 4.0.6 on 2022-11-01 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nuevavida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFuneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEntierro', models.DateField()),
                ('detalles', models.CharField(max_length=300)),
                ('cantidadBebidas', models.IntegerField()),
                ('precioBebidas', models.IntegerField()),
                ('totalBebidas', models.IntegerField()),
                ('lugarVelacion', models.CharField(max_length=100)),
                ('nombreCementerio', models.CharField(max_length=100)),
                ('cedulaUsuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Nuevavida.usuario')),
            ],
        ),
    ]
