# Generated by Django 4.1.1 on 2022-10-31 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nuevavida', '0001_initial'),
    ]

