# Generated by Django 4.1.1 on 2022-10-31 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nuevavida', '0002_detallefuneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFuneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEntierro', models.DateField()),
                ('horaInicio', models.DateTimeField()),
                ('horaFinal', models.DateTimeField()),
                ('cantidadBebidas', models.IntegerField()),
                ('precioBebidas', models.IntegerField()),
                ('totalBebidas', models.IntegerField()),
                ('lugarVelacion', models.CharField(max_length=100)),
                ('nombreCementerio', models.CharField(max_length=100)),
                ('cedulaUsuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Nuevavida.usuario')),
            ],
        ),
    ]
